name: Build Resume
on: [push]

jobs:
  build:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install conda
        uses: s-weigand/setup-conda@v1
        with:
          conda-channels: conda-forge

      - name: Install texlive-binaries
        run: sudo apt-get install texlive-binaries

      - name: Test miniconda
        run: |
          conda --version
          which python

      - name: Install Tectonic
        run: conda install tectonic
      
      - name: Test Tectonic
        run: |
          ls -1 $HOME/.cache/Tectonic
          which tectonic
          tectonic --help
      
      # This step generates the PDF file.
      #- name: Generate resume
      #  run: tectonic output.tex

     # Upload the completed resume.
      #- name: Upload resume
      #  uses: actions/upload-artifact@v1
      #  with:
      #    name: resume
      #    path: output.pdf
