name: Build Resume
on: [push]

jobs:
  build:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install conda
        uses: s-weigand/setup-conda@v1
        with:
          conda-channels: conda-forge

      - name: Install texlive-binaries
        run: sudo apt-get install texlive-binaries

      - name: Cache Tectonic
        id: cache
        uses: actions/cache@v1
        with:
          path: $CONDA
          key: tectonic

      - name: Install Tectonic
        if: steps.cache.outputs.cache-hit != 'true'
        run: conda install tectonic
      
      - name: Test Tectonic
        run: |
          echo $HOME
          echo $CONDA
          which tectonic
          [ -x "$(command -v tectonic)" ] && tectonic --help

      - name: Generate resume
        run: tectonic output.tex

     # Upload the completed resume.
      #- name: Upload resume
      #  uses: actions/upload-artifact@v1
      #  with:
      #    name: resume
      #    path: output.pdf
# [ -x "$(command -v foo)" ]
